name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.x"
      - name: Install dependencies
        run: |
          uv sync
          uv pip install coverage pytest-github-actions-annotate-failures
      - run: uv run robotpy coverage test
      - run: uv run coverage xml
      - uses: codecov/codecov-action@v4
        with:
          use_oidc: true

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.x"
      - name: Install dependencies
        run: |
          uv sync
      - name: mypy
        uses: liskin/gh-problem-matcher-wrap@v3
        with:
          linters: mypy
          run: uv run mypy --show-column-numbers .
