name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          cache: true
      - name: Install dependencies
        run: |
          pdm install
          pdm run python -m ensurepip
          pdm run python -m pip install coverage pytest-github-actions-annotate-failures
      - run: pdm run robotpy coverage test
      - run: pdm run coverage xml
      - uses: codecov/codecov-action@v3

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          cache: true
      - name: Install dependencies
        run: |
          pdm install --group typing
      - name: mypy
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: mypy
          run: pdm run mypy --show-column-numbers .
